Repository Nidec-Control-Techniques-Dev/sales-advisor-pwa, pull requests merged in 2024-04, with the labels that each got.

#12 Updated Progress Tracker Pages and Static Pages
  app/(auth)/sign-in/page.tsx
  app/about/about-card.tsx
  app/about/page.tsx
  app/dashboard/components/dashboard-navbar.tsx
  app/dashboard/layout.tsx
  app/dashboard/page.tsx
  app/dashboard/progress-schedule/page.tsx
  app/dashboard/update-progress/content.tsx
  app/dashboard/update-progress/data/progress-contents.json
  app/dashboard/update-progress/page.tsx
  components/static-page-footer.tsx
  components/static-page-navbar.tsx
  package-lock.json
  package.json
  public/nidec-all-for-dreams.webp
  tsconfig.json
  types/progress-contents.d.ts
Labels: enhancement, p1

#15 Modified package.json
  app/(auth)/sign-in/page.tsx
  app/about/about-card.tsx
  app/about/page.tsx
  app/dashboard/components/dashboard-navbar.tsx
  app/dashboard/layout.tsx
  app/dashboard/page.tsx
  app/dashboard/progress-schedule/page.tsx
  app/dashboard/update-progress/content.tsx
  app/dashboard/update-progress/data/progress-contents.json
  app/dashboard/update-progress/page.tsx
  components/static-page-footer.tsx
  components/static-page-navbar.tsx
  package-lock.json
  public/nidec-all-for-dreams.webp
  tsconfig.json
  types/progress-contents.d.ts
Labels: bug, enhancement, p1

#16 Refactored admin pages
  .vscode/settings.json
  app/dashboard/(admin)/analytics/page.tsx
  app/dashboard/(admin)/user-management/page.tsx
Labels: ui/ux, p2

#17 Integration of initial Google maps API
  app/dashboard/itinerary-maker/components/filter-companies-form.tsx
  app/dashboard/itinerary-maker/components/generate-and-save.tsx
  app/dashboard/itinerary-maker/components/starting-location-form.tsx
  app/dashboard/itinerary-maker/page.tsx
  components/autocomplete-place.tsx
  components/dynamic-map.tsx
  components/form-text-input.tsx
  components/itinerary-map.tsx
  components/select-location-map.tsx
  package-lock.json
  package.json
Labels: enhancement, p1

#18 Initial backend for User Management page
  app/dashboard/(admin)/analytics/page.tsx
  app/dashboard/(admin)/delegation/page.tsx
  components/form-select.tsx
  types/firebase/itinerary.d.ts
Labels: enhancement, p1

#20 feat: feat: get-delegation: done, filter: blocker with firestore limi…
  app/dashboard/itinerary-builder/components/filter-companies-form.tsx
  app/dashboard/itinerary-maker/components/filter-companies-form.tsx
  app/dashboard/itinerary-maker/components/generate-and-save.tsx
  app/dashboard/itinerary-maker/components/itinerary-stage-progress.tsx
  app/dashboard/itinerary-maker/components/starting-location-form.tsx
  app/dashboard/itinerary-maker/lib/create-itinerary.ts
  app/dashboard/itinerary-maker/lib/filter-companies.ts
  app/dashboard/itinerary-maker/lib/get-delegations.ts
  app/dashboard/itinerary-maker/page.tsx
  types/firebase/company/company_address.d.ts
Labels: enhancement, p1

#22 admin view updates
  app/dashboard/(admin)/analytics/page.tsx
  app/dashboard/(admin)/delegation/page.tsx
  components/client-list-table.tsx
  components/form-select.tsx
  types/firebase/itinerary.d.ts
Labels: enhancement, p1

#25 Itinerary generation
  app/dashboard-v2-deprecated/itinerary-maker/components/generate-and-save.tsx
  app/dashboard/itinerary-builder/components/filter-companies-form.tsx
  app/dashboard/itinerary-builder/components/generate-and-save.tsx
  app/dashboard/itinerary-builder/components/itinerary-stage-progress.tsx
  app/dashboard/itinerary-builder/components/starting-location-form.tsx
  app/dashboard/itinerary-builder/lib/create-itinerary.ts
  app/dashboard/itinerary-builder/lib/filter-companies.ts
  app/dashboard/itinerary-builder/lib/get-delegations.ts
  app/dashboard/itinerary-builder/page.tsx
  app/dashboard/itinerary-maker/components/generate-and-save.tsx
  app/dashboard/itinerary-maker/components/starting-location-form.tsx
  app/dashboard/itinerary-maker/lib/create-itinerary.ts
  app/dashboard/itinerary-maker/lib/filter-companies.ts
  app/dashboard/itinerary-maker/page.tsx
  components/itinerary-map.tsx
Labels: enhancement, p1

#27 Updated Progress Tracker
  app/dashboard/progress-tracker/lib/client-list-table-progress.tsx
  app/dashboard/progress-tracker/page.tsx
Labels: enhancement, p1

#28 Itinerary builder new features + page deprecations
  app/dashboard-v2-deprecated/(admin)/analytics/page.tsx
  app/dashboard-v2-deprecated/(admin)/delegation/page.tsx
  app/dashboard-v2-deprecated/(admin)/user-management/page.tsx
  app/dashboard-v2-deprecated/itinerary-maker/page.tsx
  app/dashboard-v2-deprecated/progress-schedule/page.tsx
  app/dashboard-v2-deprecated/progress-tracker/page.tsx
  app/dashboard-v2-deprecated/update-progress/content.tsx
  app/dashboard-v2-deprecated/update-progress/page.tsx
  app/dashboard/(admin)/user-management/page.tsx
  app/dashboard/itinerary-builder/components/filter-companies-form.tsx
  app/dashboard/itinerary-builder/components/generate-and-save.tsx
  app/dashboard/itinerary-builder/components/itinerary-stage-progress.tsx
  app/dashboard/itinerary-builder/components/schedule-table.tsx
  app/dashboard/itinerary-builder/components/starting-location-form.tsx
Labels: p2
