Repository Nidec-Control-Techniques-Dev/sales-advisor-pwa, pull requests merged in 2024-03, with the labels that each got.

#5 feat: progress tacker initial static frontend
  app/dashboard/progress-tracker/page.tsx
Labels: ui/ux, p1

#3 feat: itinerary maker initial frontend
  .vscode/settings.json
  app/dashboard/itinerary-maker/page.tsx
  components/dropdown.tsx
Labels: ui/ux, p1

#6 Feat: initial admin view
  app/dashboard/(admin)/analytics/page.tsx
  package-lock.json
  package.json
  tailwind.config.ts
Labels: ui/ux, p1

#9 Static Pages Update
  app/about/page.tsx
  app/bug-report/page.tsx
  app/feedback/page.tsx
  app/frequently-asked-questions/page.tsx
  components/form-modal.tsx
  components/star-rating.tsx
  components/static-page-footer.tsx
  components/static-page-navbar.tsx
  package-lock.json
  package.json
  public/AI-Site-Logo-Sidebar.webp
  public/AI-Site-Logo.webp
  public/sales-2.webp
  public/sales.webp
Labels: enhancement, p2

#10 Admin View Updates
  .vscode/settings.json
  app/dashboard/(admin)/analytics/page.tsx
  app/dashboard/(admin)/user-management/page.tsx
  package-lock.json
  package.json
  types/svgmap.d.ts
Labels: enhancement, p1
